
def share_pods
# pod 'QWeather-SDK', '4.14'
pod 'QWeather-SDK', :path => '../'
# pod 'QWeather-SDK', :git => 'https://github.com/qwd/iOS-SDK.git'
end

target 'Example-iOS' do
  platform :ios, '11.0'
  share_pods
end

target 'Example-macOS' do
  platform :osx, '10.15'
  share_pods
end


target 'Example-watchOS' do
  platform :watchos, '4.0'
  share_pods
end



