
def share_pods
 pod 'QWeather-SDK', :git => 'https://github.com/qwd/iOS-SDK.git'
end 

target 'Exemple-iOS' do
  platform :ios, '9.0'
  share_pods
end

target 'Exemple-macOS' do
  platform :osx, '10.10'
  share_pods
end

target 'Exemple-watchOS' do
  platform :watchos, '9.0'
  share_pods
end

# target 'Exemple-watchOS' do
#   platform :watchos, '2.0'
#   share_pods
# end


