
def share_pods
 pod 'QWeather-SDK', :path => '../'
end

target 'Exemple-iOS' do
  platform :ios, '10.0'
  share_pods
end

target 'Exemple-macOS' do
  platform :osx, '10.12'
  share_pods
end

target 'Exemple-watchOS' do
  platform :watchos, '3.0'
  share_pods
end



